api_version = "2025-01"

[[extensions]]

uid = "75c2b41e-bfaf-52f7-424e-434d7c2387a799820c5a"

type = "ui_extension"
name = "reward-message"
handle = "reward-message"

[extensions.capabilities]
network_access = true

[[extensions.targeting]]
target = "purchase.thank-you.block.render"
module = "./src/index.tsx"

[[extensions.targeting]]
target = "customer-account.order-status.block.render"
module = "./src/index.tsx"

