# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ecc8f1cfd8ea660f120539d4a163929b"
name = "Follo"
application_url = "https://closer-qq8c.vercel.app"
embedded = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://closer-qq8c.vercel.app/api/auth/callback"
]

# Mandatory GDPR compliance webhooks
[privacy_compliance]
customer_data_request_url = "https://closer-qq8c.vercel.app/api/webhooks/customers/data_request"
customer_deletion_url = "https://closer-qq8c.vercel.app/api/webhooks/customers/redact"
shop_deletion_url = "https://closer-qq8c.vercel.app/api/webhooks/shop/redact"
