# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc9774a4da10e5bbbab117098c51e124"
name = "closer-reward"
application_url = "https://closer-shopify-qq8c.vercel.app/"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ "read_customers", "read_orders", "write_script_tags" ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://closer-shopify-qq8c.vercel.app/api/auth/callback",
  "https://closer-shopify-qq8c.vercel.app/exitiframe"
]

[app_proxy]
url = "https://closer-shopify-qq8c.vercel.app/api/proxy/reward"
subpath = "reward-message"
prefix = "apps"
