# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ecc8f1cfd8ea660f120539d4a163929b"
name = "Follo"
application_url = "https://closer-qq8c.vercel.app"
embedded = true

[webhooks]
api_version = "2025-10"

# App lifecycle webhook
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks/app/uninstalled"

# Mandatory GDPR compliance webhooks
[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://closer-qq8c.vercel.app/api/webhooks"

[access_scopes]
scopes = "read_orders,write_orders,read_products,write_order_edits,write_payment_terms,read_payment_terms"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://closer-qq8c.vercel.app/api/auth/callback"
]
