# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ecc8f1cfd8ea660f120539d4a163929b"
name = "Follo"
application_url = "https://closer-qq8c.vercel.app"
embedded = true

[webhooks]
api_version = "2025-10"
[[webhooks]]
topic = "CUSTOMERS_DATA_REQUEST"
address = "/api/webhooks/customers/data_request"
format = "json"

[[webhooks]]
topic = "CUSTOMERS_REDACT"
address = "/api/webhooks/customers/redact"
format = "json"

[[webhooks]]
topic = "SHOP_REDACT"
address = "/api/webhooks/shop/redact"
format = "json"

[[webhooks]]
topic = "APP_UNINSTALLED"
address = "/api/webhooks/app/uninstalled"
format = "json"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://closer-qq8c.vercel.app/api/auth/callback"
]
